### ISSUE TITLE
Errors do not stop builds on "workflow_call"

### ISSUE THREAD

**Issue by miguelb-gk** [morphy2k/revive-action#103]
We are trying to add this action as part of our CI process and its succeeds even though there are errors.

GHA yml file...
```
name: Go Code Quality Checks
on:
  workflow_call:
    inputs:
      SHA:
        description: "full sha to build"
        type: string
        required: true

jobs:
  Checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          ref: ${{ inputs.sha }}

      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2
        with:
          config: revive.toml
```

The job succeeds with this message...
`Successful run with 95 failures (0 warnings, 95 errors)`

**Comment by morphy2k** [comment]
The exit code in the configuration file may not be set correctly. For the job to fail, the code must be greater than zero.

### Example
```TOML
errorCode = 1
warningCode = 1
```

I am closing the issue for now.
