### ISSUE TITLE
`fail-on-any` parameter incorrectly passed to Docker container

### ISSUE THREAD

**Issue by bigSiebs** [morphy2k/revive-action#157]
When using the basic configuration below, I see that `-e "INPUT_FAIL-ON-ANY"` is passed to the Docker container, but input.go is looking for ["INPUT_FAIL_ON_ANY"](https://github.com/morphy2k/revive-action/blob/master/input.go#L15) when checking this option.
```
name: pr

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        uses: docker://morphy/revive-action:v2.7.1
        with:
          config: .revive.toml
          fail-on-any: true
```

To fix it, either input.go's constant needs to reflect what's actually being passed, or the configuration parameter needs to be changed to `fail_on_any` in the docs. I'm currently working around the issue by using `fail_on_any` in my workflow. I'd submit a PR, but I don't know which solution is preferable.

BTW: Thanks for your work on this action. My team finds it very helpful.
